services:
  api:
    build: .
    container_name: ai-chatbot-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  mongo:
    image: mongo:7
    container_name: ai-chatbot-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./data:/data
      - ./docker/mongo-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: company_db

volumes:
  mongo_data:
